web:
  build: .
  links:
   - db
  ports:
   - "30:3000"
  volumes:
   - .:/usr/src/app/
  environment:
   NODE_ENV: production
   MONGO_URL: mongodb://db:27017/UserDbForm
db:
  image: mongo:latest
  ports:
   - "27017:27017"

